EE_BIN  = alpha.elf
EE_OBJS = alpha.o

LIBGSKIT = $(GSKIT)/lib/libgskit.a
LIBDMAKIT = $(GSKIT)/lib/libdmakit.a
LIBGSKIT_TOOLKIT = $(GSKIT)/lib/libgskit_toolkit.a
# GSKIT_DEBUG = 1
LIBJPEG = $(PORTS)/libjpeg
LIBTIFF = $(PORTS)/libtiff
LIBPNG = $(PORTS)/libpng
ZLIB = $(PORTS)/zlib

include ../../../../makers/gskit.make
